version: '3'
services:
  composer:
    container_name: stwarog-uow-fuel
    image: composer:2.0
    environment:
      - COMPOSER_CACHE_DIR=/app/.cache/composer
    volumes:
      - .:/app
    entrypoint: composer
